#Data Load
library(readxl)
library(readr)
MyData <- read_csv("C:/Users/MICTDATASCIE01/Desktop/R scripts/WEBOC/WEBOC2020.csv")
View(MyData)
MyData <- data.frame(MyData)
a=colnames(MyData)

MyData$Consignee=gsub("(1)", "", MyData$Consignee)
MyData$Consignee=gsub(")", "", MyData$Consignee)
MyData$Consignee=gsub("[(]", "", MyData$Consignee)
MyData$Consignee=gsub("[#]", "", MyData$Consignee)
MyData$Consignee=gsub("[-]", "", MyData$Consignee)

#remove numbers, remove misspell with provided Dictionary,
MyData$Consignee=gsub("1 ", "", MyData$Consignee)
MyData$Consignee=gsub(" 1 ", "", MyData$Consignee)
MyData$Consignee=gsub("0000 ", "", MyData$Consignee)
MyData$Consignee=gsub("M S ", "", MyData$Consignee)
MyData$Consignee=gsub("1|\u623c|\u3e66", "", MyData$Consignee)
MyData$Consignee=gsub("0", "", MyData$Consignee)
MyData$Consignee=gsub("PRIVATE", "PVT", MyData$Consignee)
MyData$Consignee=gsub("LIMITED", "LTD", MyData$Consignee)
MyData$Consignee=gsub("CHEMICALS", "CHEMICAL", MyData$Consignee)
MyData$Consignee=gsub("STEELS", "STEEL", MyData$Consignee)
MyData$Consignee=gsub("BROTHERSS", "BROTHERS", MyData$Consignee)
MyData$Consignee=gsub("BROTHER", "BROTHERS", MyData$Consignee)
MyData$Consignee=gsub("S O", "S/O", MyData$Consignee)
MyData$Consignee=gsub("(PVT)", "PVT", MyData$Consignee)
MyData$Consignee=gsub("ENTERPRISES", "ENTERPRISE", MyData$Consignee)
MyData$Consignee=gsub("PVTLTD", "PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("PAKISTAN", "PAK", MyData$Consignee)
MyData$Consignee=gsub("BUSINESSES", "BUSINESS", MyData$Consignee)
MyData$Consignee=gsub("TEXTILES", "TEXTILE", MyData$Consignee)
MyData$Consignee=gsub("INDUSTRIES", "INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("TRADINGS", "TRADING", MyData$Consignee)
MyData$Consignee=gsub("2 ", "", MyData$Consignee)
MyData$Consignee=gsub("(MAIN).*", "", MyData$Consignee)
MyData$Consignee=gsub("(PVT).*", "PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(LTD).*", "LTD", MyData$Consignee)
MyData$Consignee=gsub("(M S )", "", MyData$Consignee)
MyData$Consignee=gsub("(PVT).*", "PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(PVT LTD).*", "PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(LTD ).*", "LTD", MyData$Consignee)
MyData$Consignee=gsub("(SUIT).*", "PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(CORPORATION PVT LTD).*", "CORPORATION PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(MAIN).*", "", MyData$Consignee)
MyData$Consignee=gsub("(ENTERPR).*", "ENTERPRISE", MyData$Consignee)
MyData$Consignee=gsub("252387", "", MyData$Consignee)
MyData$Consignee=gsub("(CORPORATION PVT LTD).*", "CORPORATION PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(MILLS LTD).*", "MILLS LTD", MyData$Consignee)
MyData$Consignee=gsub("(PHARMACY).*", "PHARMACY", MyData$Consignee)
MyData$Consignee=gsub("(PHARMACE).*", "PHARMACEUTICALS", MyData$Consignee)
MyData$Consignee=gsub("5", "", MyData$Consignee)
MyData$Consignee=gsub("6", "", MyData$Consignee)
MyData$Consignee=gsub("8", "", MyData$Consignee)
MyData$Consignee=gsub("1", "", MyData$Consignee)
MyData$Consignee=gsub("(H NO).*", "", MyData$Consignee)
MyData$Consignee=gsub("(FLOOR).*", "", MyData$Consignee)
MyData$Consignee=gsub("(BLOCK).*", "", MyData$Consignee)
MyData$Consignee=gsub("  ", " ", MyData$Consignee)
MyData$Consignee=gsub("COMPANYPVT", "COMPANY PVT", MyData$Consignee)
MyData$Consignee=gsub("RE ROLLING", "REROLLING", MyData$Consignee)
MyData$Consignee=gsub("(DEPOT EME).*", "DEPOT EME", MyData$Consignee)
MyData$Consignee=gsub("SPARE", "SPARES", MyData$Consignee)
MyData$Consignee=gsub("3STARS", "3STAR", MyData$Consignee)
MyData$Consignee=gsub("SPARESS", "SPARES", MyData$Consignee)
MyData$Consignee=gsub("POLYMERSPVT", "POLYMERS PVT", MyData$Consignee)
MyData$Consignee=gsub("ENGINEERINGPVT", "ENGINEERING PVT", MyData$Consignee)
MyData$Consignee=gsub("MERCHANDISINGPVT", "MERCHANDISING PVT", MyData$Consignee)
MyData$Consignee=gsub("(AL RUMAN GR).*", "AL RUMAN GRAPHICS AND PACKAGING", MyData$Consignee)
MyData$Consignee=gsub("(AL SADIQ J T IND).*", "AL SADIQ J T INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("(AL SAEED).*", "AL SADIQ J T INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("2", "2 ", MyData$Consignee)
MyData$Consignee=gsub("3", "3 ", MyData$Consignee)
MyData$Consignee=gsub("4", "4 ", MyData$Consignee)
MyData$Consignee=gsub("9", "9 ", MyData$Consignee)
MyData$Consignee=gsub("9 9", "99 ", MyData$Consignee)
MyData$Consignee=gsub("   ", " ", MyData$Consignee)
MyData$Consignee=gsub("  ", " ", MyData$Consignee)
MyData$Consignee=gsub("3 3", "33", MyData$Consignee)
MyData$Consignee=gsub("FOODSINDUSTRY", "FOODS INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("FOOD", "FOODS", MyData$Consignee)
MyData$Consignee=gsub("FOODSSPVT", "FOODS PVT", MyData$Consignee)
MyData$Consignee=gsub("FOODSS", "FOODS", MyData$Consignee)
MyData$Consignee=gsub("FOODSSYSTEMS", "FOODS SYSTEMS", MyData$Consignee)
MyData$Consignee=gsub("FOODSSERVICES", "FOODS SERVICES", MyData$Consignee)
MyData$Consignee=gsub("FOODSSOLUTIONS", "FOODS SOLUTIONS", MyData$Consignee)
MyData$Consignee=gsub("ENTERPRISESS", "ENTERPRISE", MyData$Consignee)
MyData$Consignee=gsub("(AA FOODS).*", "AA FOODS PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("MIL LS", "MILLS", MyData$Consignee)
MyData$Consignee=gsub("PAHRMA", "PHARMA", MyData$Consignee)
MyData$Consignee=gsub("(CENTER).*", "CENTER", MyData$Consignee)
MyData$Consignee=gsub("(ADDRESS).*", "", MyData$Consignee)
MyData$Consignee=gsub("(G 99).*", "", MyData$Consignee)
MyData$Consignee=gsub("(BHATTRA).*", "BHATTRA SONS", MyData$Consignee)
MyData$Consignee=gsub("(PESTICID).*", "PESTICIDES", MyData$Consignee)
MyData$Consignee=gsub("(A B SONS SEE).*", "A B SONS SEED PESTICIDES", MyData$Consignee)




#remove leading and trailing spaces
trim.trailing <- function (x) sub("\\s+$", "", x)
MyData$Consignee <- trim.trailing(MyData$Consignee)
trim.leading <- function (x)  sub("^\\s+", "", x)
MyData$Consignee <- trim.leading(MyData$Consignee)

#remove punctuation
MyData$Consignee=gsub('[[:punct:]]',' ',MyData$Consignee)

#remove leading and trailing spaces
trim.trailing <- function (x) sub("\\s+$", "", x)
MyData$Consignee <- trim.trailing(MyData$Consignee)
trim.leading <- function (x)  sub("^\\s+", "", x)
MyData$Consignee <- trim.leading(MyData$Consignee)

#REMOVE address
MyData$Consignee=gsub("(SHOP NO).*", "", MyData$Consignee)
MyData$Consignee=gsub("(SHOP ).*", "", MyData$Consignee)
MyData$Consignee=gsub("(SHOPNO ).*", "", MyData$Consignee)
MyData$Consignee=gsub("(SHOPP).*", "", MyData$Consignee)
MyData$Consignee=gsub("(SHOP).*", "", MyData$Consignee)
MyData$Consignee=gsub("(MAIN).*", "", MyData$Consignee)
MyData$Consignee=gsub("(HOUSE ).*", "", MyData$Consignee)
MyData$Consignee=gsub("(PLOT).*", "", MyData$Consignee)
MyData$Consignee=gsub("(POLT ).*", "", MyData$Consignee)
MyData$Consignee=gsub("(NTN ).*", "", MyData$Consignee)
MyData$Consignee=gsub("(OFFICE).*", "", MyData$Consignee)
MyData$Consignee=gsub("(ROOM).*", "", MyData$Consignee)
MyData$Consignee=gsub("(FURNACE).*", "FURNACE", MyData$Consignee)
MyData$Consignee=gsub("(SUIT).*", "", MyData$Consignee)
MyData$Consignee=gsub("STEL ", "STEEL", MyData$Consignee)
MyData$Consignee=gsub("FOODS", "FOOD", MyData$Consignee)
MyData$Consignee=gsub("FOOD ", "FOODS", MyData$Consignee)
MyData$Consignee=gsub("(SHOPNO).*", "", MyData$Consignee)
MyData$Consignee=gsub("(626 SHOPP).*", "", MyData$Consignee)
MyData$Consignee=gsub("(SHOP).*", "", MyData$Consignee)
MyData$Consignee=gsub("(SUIT).*", "", MyData$Consignee)
MyData$Consignee=gsub("LABORATORY.*", "LABORATORY", MyData$Consignee)
MyData$Consignee=gsub("LABORATORI.*", "LABORATORIES", MyData$Consignee)

#remove Company Name duplicate
MyData$Consignee <- gsub("^(MUHAMMAD & CO).*", "MUHAMMAD & CO", MyData$Consignee)
MyData$Consignee <- gsub("^(3M PAKISTAN).*", "3M PAKISTAN PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(4 STAR IMPEX).*", "4 STAR IMPEX", MyData$Consignee)
MyData$Consignee <- gsub("^(7 TRADER).*", "7 TRADER", MyData$Consignee)
MyData$Consignee <- gsub("^(99 STAR CORPORATION).*", "99 STAR CORPORATION", MyData$Consignee)
MyData$Consignee <- gsub("^(A LINE INTERNATIONAL).*", "A LINE INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A & H GARMENT).*", "A & H GARMENT", MyData$Consignee)
MyData$Consignee <- gsub("^(A & W ENTERPRISES).*", "A & W ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A AND R COMPANY).*", "A AND R COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A LINE INTERNATIONAL).*", "A LINE INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A ONE TECHNIQUES).*", "A ONE TECHNIQUES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A ONE FEEDS).*", "A ONE FEEDS", MyData$Consignee)
MyData$Consignee <- gsub("^(ACCRESCENT ENGINEERS).*", "ACCRESCENT ENGINEERS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(MV RIVER KING MASTE).*", "MV RIVER KING MASTER", MyData$Consignee)
MyData$Consignee <- gsub("^(A.R. STEEL INDUSTRY).*", "A.R STEEL INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(ZZ TRADERS).*", "ZZ TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(4-BROTHER).*", "4 BROTHERS INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A A TRADER).*", "A A TRADER", MyData$Consignee)
MyData$Consignee <- gsub("^(1 M S M A S ENTERPRISES).*", "M S ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(M S ENTERPRISES).*", "M S ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(1 SKF COLLECTION).*", "SKF COLLECTION", MyData$Consignee)
MyData$Consignee <- gsub("^(SKF COLLECTION).*", "SKF COLLECTION", MyData$Consignee)
MyData$Consignee <- gsub("^(SKF PAKISTAN).*", "SKF COLLECTION", MyData$Consignee)
MyData$Consignee <- gsub("^(SK TRADING).* | ^(SK TRADERS).*", "SK TRADING", MyData$Consignee)
MyData$Consignee <- gsub("^(SK TRADERS).*", "SK TRADING", MyData$Consignee)
MyData$Consignee <- gsub("^(SKIMS PHARMACEUTICAL).*", "SKIMS PHARMACEUTICAL", MyData$Consignee)
MyData$Consignee <- gsub("^(SKINCARE COMPANY).*", "SKIN CARE COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(1 M S M A S ENTERPRISES).*", "M S ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A B INTERNATIONAL).*", "A B INTERNATIONAL AGENCY", MyData$Consignee)
MyData$Consignee <- gsub("^(2 STAR).*", "2 STAR INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(3 STAR).*", "3 STAR CHEMICALS", MyData$Consignee)
MyData$Consignee <- gsub("^(301 SPARE).*", "301 SPARES DEPOT EME", MyData$Consignee)
MyData$Consignee <- gsub("^(1 DEWAN MOTORS).*", "DEWAN MOTORS PRIVATE LIMITED", MyData$Consignee)
MyData$Consignee <- gsub("^(DEWAN MOTORS).*", "DEWAN MOTORS PRIVATE LIMITED", MyData$Consignee)
MyData$Consignee <- gsub("^(2 STAR).*", "2 STAR INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(3 STAR).*", "3 STAR CHEMICALS", MyData$Consignee)
MyData$Consignee <- gsub("^(CHINA GEZHOUBA).*", "CHINA GEZHOUBA GROUP", MyData$Consignee)
MyData$Consignee <- gsub("^(ZYNAH).*", "ZYNAH ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(ZXMCO).*", "ZXMCO PAKISTAN PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ZURAM).*", "ZURAM BROTHERS", MyData$Consignee)
MyData$Consignee <- gsub("^(ZUMZUM).*", "ZUMZUM STEEL", MyData$Consignee)
MyData$Consignee <- gsub("^(ZUM ZUM).*", "ZUMZUM STEEL", MyData$Consignee)
MyData$Consignee <- gsub("^(ZYMOTIC).*", "ZYMOTIC DIAGNOSTICS INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(ZUNAIR).*", "ZUNAIR ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(ZULTEC).*", "ZULTEC PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ZULQUIRNAIN).*", "ZULQUIRNAIN CORPORATION", MyData$Consignee)
MyData$Consignee <- gsub("^(ZULFIQAR INDUSTRIES).*", "ZULFIQAR INDUSTRIES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(1 DOW FABRICS).*", "DOW FABRICS", MyData$Consignee)
MyData$Consignee <- gsub("^(1 ICI).*", "ICI PAKISTAN LIMITED", MyData$Consignee)
MyData$Consignee <- gsub("^(M S ICI PAKISTAN).*", "ICI PAKISTAN LIMITED", MyData$Consignee)
MyData$Consignee <- gsub("^(ZULFIQAR ALI SAAB).*", "ZULFIQAR ALI SAAB TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR SUGAR).*", "AL NOOR SUGAR MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR SHIPPERS).*", "AL NOOR SHIPPERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR PROCESSING).*", "AL NOOR PROCESSING", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR PETROLEUM).*", "AL NOOR PETROLEUM", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR OIL).*", "AL NOOR OIL EXTRACTION PLANT PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR INTERNATIONAL).*", "AL NOOR INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR INDUSTRIES).*", "AL NOOR INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR GLOBAL).*", "AL NOOR GLOBAL", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR ENTERPRISES).*", "AL NOOR ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR CHEMICALS).*", "AL NOOR CHEMICALS", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NOOR AGRO).*", "AL NOOR AGRO CHEMICALS ", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NASR).*", "AL NASR TEXTILES LIMITED ", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NASIR MOTORS).*", "AL NASIR MOTORS", MyData$Consignee)
MyData$Consignee <- gsub("^(AL NAKHEEL).*", "AL NAKHEEL AFGHAN LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A A FABRIC).*", "A A FABRICS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A A INDUSTRIES).*", "A A INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(A A TYRE).*", "A A TYRE COPORATION", MyData$Consignee)
MyData$Consignee <- gsub("^(A F STEEL).*", "A F STEEL RE ROLLING MILLS", MyData$Consignee)
MyData$Consignee <- gsub("^(A FEROZ).*", "A FEROZ AND CO", MyData$Consignee)
MyData$Consignee <- gsub("^(A G ENTERPRISES).*", "A G ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(NESTACC NATIONAL).*", "NESTACC NATIONAL ENGINEERING SERVICES", MyData$Consignee)
MyData$Consignee <- gsub("^(A A  ENTERPRISES).*", "A A  ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A A TYRE).*", "A A TYRE COPORATION", MyData$Consignee)
MyData$Consignee <- gsub("^(A A PAPER).*", "A A PAPER PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A B EXPORTS).*", "A B EXPORTS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A B SAEED).*", "A B SAEED PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDUL HAFEEZ).*", "ABDUL HAFEEZ ", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDUL GHAFFAR KHAN).*", "ABDUL GHAFFAR KHAN", MyData$Consignee)
MyData$Consignee <- gsub("^(ABC RAG).*", "ABC RAG COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(ABCO TECHNICAL PVT LTD).*", "ABCO TECHNICAL PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDOOL).*", "ABDOOLALLY MOOSABHHOY SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(1 ORIENT ELEC).*", "ORIENT ELECTRONICS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A H Y PLASTIC).*", "A H Y PALSTIC INDUSTRY PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A I TEX).*", "A I TEXTILES", MyData$Consignee)
MyData$Consignee <- gsub("^(AMRELI).*", "AMRELI STEELS LID", MyData$Consignee)
MyData$Consignee <- gsub("^(AMROZ).*", "AMROS PHARMACEUTICAL", MyData$Consignee)
MyData$Consignee <- gsub("^(AMROS).*", "AMROS PHARMACEUTICAL", MyData$Consignee)
MyData$Consignee <- gsub("^(4 STARS).*", "4 STARS INTERATIONAL TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(4 STAR).*", "4 STARS INTERATIONAL TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(4A INT).*", "4A INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(7 TRADER).*", "7 STAR TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(7 STAR).*", "7 STAR TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A J TEXTILE).*", "A J TEXTILE MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A J TRADING).*", "A J TRADING PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A J TRADERS).*", "A J TRADING PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A J NAWAB).*", "A J NAWAB AND CO", MyData$Consignee)
MyData$Consignee <- gsub("^(A J STEEL).*", "A J STEEL WIRE INDUSTRIES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A J SYNTHETIC).*", "A J SYNTHETIC FOOTWARE INDUSTRIES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A K ENTERPRISES).*", "A K ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(4 STARS).*", "4 STARS INTERATIONAL TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(4WALLS).* ", "4 WALLS PRIVATE LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(4 WALLS).*", "WALLS PRIVATE LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(NO 103 ALC PAF).*", "NO 103 ALC PAF NUR KHAN", MyData$Consignee)
MyData$Consignee <- gsub("^(101ALC).*", "NO 103 ALC PAF NUR KHAN", MyData$Consignee)
MyData$Consignee <- gsub("^(103 ALC).*", "NO 103 ALC PAF NUR KHAN", MyData$Consignee)
MyData$Consignee <- gsub("^(10ALC).*", "NO 103 ALC PAF NUR KHAN", MyData$Consignee)
MyData$Consignee <- gsub("^(SERVICE).*", "M S SERVICE INDUSTRIES LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(DAWOOD AND SONS).*", "DAWOOD AND SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(DAWOOD DYES).*", "DAWOOD DYES AND CHEMICALS", MyData$Consignee)
MyData$Consignee <- gsub("^(FMC).*", "FMC UNITED PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(3 STEP).*", "3 STEP", MyData$Consignee)
MyData$Consignee <- gsub("^(4 BROTHER).*", "4 BROTHER INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A D IMPEX).*", "A D IMPEX SUITE", MyData$Consignee)
MyData$Consignee <- gsub("^(A B TRADERS).*", "A B TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A B TRADING).*", "A B TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A C T AIR).*", "A C T AIR COMPRESSOR TECHNOLOGY", MyData$Consignee)
MyData$Consignee <- gsub("^(A A FOODS).*", "A A FOODS IMPORTERS DISTRIBUTORS", MyData$Consignee)
MyData$Consignee <- gsub("^(A A ENT).*", "A A ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A A ASSAC).*", "A A ASSAC COMPANY PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A A COTTON).*", "A A COTTON MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A A M INTERNATIONAL).*", "A A M INTERNATIONAL IMPORTER", MyData$Consignee)
MyData$Consignee <- gsub("^(A AND Z).*", "A AND Z AGRO INDUSTRIES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A B AND C).*", "A B AND COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A B COMPANY).*", "A B AND COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A B AND SONS).*", "A B AND COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A B FOOD).*", "A B FOOD INDUSTRIES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A B MEMON).*", "A B MEMON SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(A B S ENG).*", "A B S ENGINEERING CORPORATION PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A B SAEED).*", "A B SONS SEEDS PESTICIDES", MyData$Consignee)
MyData$Consignee <- gsub("^(A B SONS).*", "A B SONS SEEDS PESTICIDES", MyData$Consignee)
MyData$Consignee <- gsub("^(A B STEELS).*", "A B STEELS", MyData$Consignee)
MyData$Consignee <- gsub("^(A B TE).*", "A B TECH", MyData$Consignee)
MyData$Consignee <- gsub("^(A ESSAK).*", "A ESSAK AND SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(A F AND SONS).*", "A F SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(A F TRAD).*", "A F TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A G STEEL).*", "A G STEEL FURNACE", MyData$Consignee)
MyData$Consignee <- gsub("^(A H CASHMERE).*", "A H CASHMERE WOOL IMPEX", MyData$Consignee)
MyData$Consignee <- gsub("^(A H ENT).*", "A H ENTERPRISE", MyData$Consignee)
MyData$Consignee <- gsub("^(A H GARM).*", "A H GARMENTS", MyData$Consignee)
MyData$Consignee <- gsub("^(A H INTER).*", "A H INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A H M ENT).*", "A H M ENTERPRISESS", MyData$Consignee)
MyData$Consignee <- gsub("^(A H TRAD).*", "A H TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A I TRAD).*", "A I TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A INNO).*", "A INNOVATIVE EQUIPMENT", MyData$Consignee)
MyData$Consignee <- gsub("^(A J ENT).*", "A J ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A J MATCH).*", "A J MATCH PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A J TEXT).*", "A J TEXTILE MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A K DYE).*", "A K DYEING", MyData$Consignee)
MyData$Consignee <- gsub("^(A K ENTE).*", "A K ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A K IND).*", "A K INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(A K INT).*", "A K INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A K STEEL).*", "A K STEEL RE ROLLING MILLS", MyData$Consignee)
MyData$Consignee <- gsub("^(A K TAR).*", "A K TARIQ FOUNDARY", MyData$Consignee)
MyData$Consignee <- gsub("^(A K TRAD).*", "A K TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A KAR).*", "A KARIMJEE SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(A J TEXT).*", "A J TEXTILE MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A M ASSO).*", "A M ASSOCAITES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A M ENT).*", "A M ENTERPRISESS", MyData$Consignee)
MyData$Consignee <- gsub("^(A M INTE).*", "A M INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A M K ENGINEERING PVT LTD).*", "A M K STEEL PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A M K STEEL).*", "A M K STEEL PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A M R ENT).*", "A M R ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A M SA).*", "A M SAEED CO", MyData$Consignee)
MyData$Consignee <- gsub("^(A M STE).*", "A M STEEL FURNACE RE ROLLING", MyData$Consignee)
MyData$Consignee <- gsub("^(A M TRAD).*", "A M TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A M YOUSUF).*", "A M YOUSUF AND CO", MyData$Consignee)
MyData$Consignee <- gsub("^(A MAJEED).*", "A MAJEED AND COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A MASOOD).*", "A MASOOD TEXTILE MILLS LIMITED", MyData$Consignee)
MyData$Consignee <- gsub("^(A N SOURCING).*", "A N SOURCING ANGORA TEXTILE MILLS", MyData$Consignee)
MyData$Consignee <- gsub("^(A N TEXTILE).*", "A N TEXTILE MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A N TRAD).*", "A N TRADERS AND DEVELOPERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A N WORLD).*", "A N WORLDWIDE TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A ONE RE).*", "A ONE RE ROLLING MILLS", MyData$Consignee)
MyData$Consignee <- gsub("^(A ONE TEXT).*", "A ONE TEXTILE AND TOWEL INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(A POLY).*", "A POLY INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(A Q CO).*", "A Q COMPANY INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A R ASSOCIATES).*", "A R ASSOCIATES", MyData$Consignee)
MyData$Consignee <- gsub("^(A R BRO).*", "A R BROTHERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A R COMPUT).*", "A R COMPUTERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A R ENTER).*", "A R ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A R INDU).*", "A R INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(A R INTE).*", "A R INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A R STEEL).*", "A R STEEL INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(A R TEXTIL).*", "A R TEXTILES", MyData$Consignee)
MyData$Consignee <- gsub("^(A R TRADER).*", "A R TRADERS INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A R TRADING).*", "A R TRADING", MyData$Consignee)
MyData$Consignee <- gsub("^(A RAZA).*", "A RAZA ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A S AUTO).*", "A S AUTO INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(A S COMPANY).*", "A S COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(A S COMPUT).*", "A S COMPUTERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A S ENTER).*", "A S ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A S EXPRESS).*", "A S EXPRESS", MyData$Consignee)
MyData$Consignee <- gsub("^(A S INTER).*", "A S INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(A S SCRAP).*", "A S SCRAP DEALER", MyData$Consignee)
MyData$Consignee <- gsub("^(A S TRADE).*", "A S TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A S TRADI).*", "A S TRADING CORPORATION", MyData$Consignee)
MyData$Consignee <- gsub("^(A SALAM CO).*", "A SALAM CO", MyData$Consignee)
MyData$Consignee <- gsub("^(A SAPPHIRE FIBRES).*", "A SAPPHIRE FIBRES LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A T C TRAD).*", "A T C TRADING CO", MyData$Consignee)
MyData$Consignee <- gsub("^(A T COTTEX).*", "A T COTTEX", MyData$Consignee)
MyData$Consignee <- gsub("^(A T ENTER).*", "A T ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A T H ENTER).*", "A T H ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A T S SYNTH).*", "A T S SYNTHETHIC PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A TO Z HOS).*", "A TO Z HOSIERY", MyData$Consignee)
MyData$Consignee <- gsub("^(A TO ZEE SWITCH).*", "A TO ZEE SWITCHGEAR ENGINEERING SMC PVTLTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A TRADER).*", "A TRADER", MyData$Consignee)
MyData$Consignee <- gsub("^(A W ENG).*", "A W ENGINEERING PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A W ENTER).*", "A W ENTERPRISE", MyData$Consignee)
MyData$Consignee <- gsub("^(A WAHAB TRAD).*", "A WAHAB TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(A Z APPAREL).*", "A Z APPAREL PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A Z CORP).*", "A Z CORPORATION", MyData$Consignee)
MyData$Consignee <- gsub("^(A Z ENTER).*", "A Z ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(A Z PHARM).*", "A Z PHARMACEUTICALS CO LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A99 TRAD).*", "A99 TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(AA CO).*", "AA COTTON MILLS LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AA ENTERPRISES).*", "AA ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(AA FABRICS).*", "AA FABRICS", MyData$Consignee)
MyData$Consignee <- gsub("^(AA FOODS).*", "AA FOODS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AA IMPEX).*", "AA IMPEX", MyData$Consignee)
MyData$Consignee <- gsub("^(AA PAPER).*", "AA PAPER PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AA PROCESSING).*", "AA PROCESSING INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(AA TRAD).*", "AA TRADER", MyData$Consignee)
MyData$Consignee <- gsub("^(AAA INTERN).*", "AAA INTERNATIONAL INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(AAA PACKA).*", "AAA PACKAGES", MyData$Consignee)
MyData$Consignee <- gsub("^(AAA PLASTIC).*", "AAA PLASTIC PRODUCTS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AAA TRAD).*", "AAA TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AABI TRADERS).*", "AABI TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AAHYAN TRADE).*", "AAHYAN TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AAJ BRO).*", "AAJ BROTHERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AAK ).*", "AAK TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(AAKASH KUMAR).*", "AAKASH KUMAR", MyData$Consignee)
MyData$Consignee <- gsub("^(AALA PROCESSING).*", "AALA PROCESSING INDUSTRIES PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AAM INTER).*", "AAM INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(AAMENA ENTERPRI).*", "AAMENA ENTERPRISE", MyData$Consignee)
MyData$Consignee <- gsub("^(AAMIR AND SONS).*", "AAMIR AND SONS", MyData$Consignee)
MyData$Consignee <- gsub("^(AAMIR BRO).*", "AAMIR BROTHER", MyData$Consignee)
MyData$Consignee <- gsub("^(AAMIR FAROOQ).*", "AAMIR FAROOQ", MyData$Consignee)
MyData$Consignee <- gsub("^(AAMNA ENTER).*", "AAMNA ENTERPRISES SHO", MyData$Consignee)
MyData$Consignee <- gsub("^(AAMSTER LAB).*", "AAMSTER LABORATORIES", MyData$Consignee)
MyData$Consignee <- gsub("^(AAN POLY).*", "AAN POLYVINYL INDUSTRIES", MyData$Consignee)
MyData$Consignee <- gsub("^(AAQIB ENTE).*", "AAQIB ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(AASHER TRAD).*", "AASHER TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(AFAQ STEEL).*", "AFAQ STEEL", MyData$Consignee)
MyData$Consignee <- gsub("^(AASIF ENT).*", "AASIF ENTERPRISES", MyData$Consignee)
MyData$Consignee <- gsub("^(AAYAAN INTER).*", "AAYAAN INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(AAZ ENTERPRIS).*", "AAZ ENTERPRISE", MyData$Consignee)
MyData$Consignee <- gsub("^(AB BRANDS).*", "AB BRANDS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A AND S/OIL ).*", "A AND S OIL INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(AB MAURI).*", "AB MAURI PAKISTAN PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AB METAL WORKS).*", "AB METAL WORKS PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AB PAKISTAN INTERNATIONAL).*", "AB PAKISTAN INTERNATIONAL", MyData$Consignee)
MyData$Consignee <- gsub("^(AAHYAN TRADE).*", "AAHYAN TRADERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AAJ BRO).*", "AAJ BROTHERS", MyData$Consignee)
MyData$Consignee <- gsub("^(AAK ).*", "AAK TRADING COMPANY", MyData$Consignee)
MyData$Consignee <- gsub("^(AAKASH KUMAR).*", "AAKASH KUMAR", MyData$Consignee)
MyData$Consignee <- gsub("^(AB MAURI).*", "AB MAURI PAK PVT", MyData$Consignee)
MyData$Consignee <- gsub("^(ADEN).*", "ADENWALLA SON", MyData$Consignee)
MyData$Consignee <- gsub("^(DURRANI ENTE).*", "DURRANI ENTERPRISE", MyData$Consignee)
MyData$Consignee <- gsub("^(ABOOTT LABORAORIES PAK LTD).*", "ABBOTT LABORATORIES LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AGHA STEEL).*", "AGHA STEEL INDUSTRY LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDUL GHAFFAR STEEL).*", "ABDUL GHAFFAR STEEL INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDUL HAMEED STEEL).*", "ABDUL HAMEED STEEL", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDULLAH BROTHERS).*", "ABDULLAH BROTHERS", MyData$Consignee)
MyData$Consignee <- gsub("^(ABDULLAH HASEEB AGR).*", "ABDULLAH HASEEB AGRO", MyData$Consignee)
MyData$Consignee <- gsub("^(THE SHOE).*", "THE SHOE SHOP", MyData$Consignee)
MyData$Consignee <- gsub("^(AL SAYEED BROTHERS CORP).*", "AL SAYEED BROTHERS CORP", MyData$Consignee)
MyData$Consignee <- gsub("^(ZUBAIR CO).*", "ZUBAIR CO", MyData$Consignee)
MyData$Consignee <- gsub("^(PAK ELEKTRO).*", "PAK ELEKTRON LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(MUGHAL IRON AND STEEL).*", "MUGHAL IRON AND STEEL INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(UNILEVER PAK).*", "UNILEVER PAK LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(HNR COMPANY).*", "HNR COMPANY PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(INDUS MOTOR COMPANY LTD).*", "INDUS MOTOR COMPANY LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(THE SHOE HOME).*", "THE SHOE", MyData$Consignee)
MyData$Consignee <- gsub("^(THE SHOE).*", "THE SHOE SHOP", MyData$Consignee)
MyData$Consignee <- gsub("^(3SPARES DEP).*", "3SPARES DEPOT", MyData$Consignee)
MyData$Consignee <- gsub("^(COLGATE PALM).*", "COLGATE PALMOLIVE PAK LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(NESTLE).*", "NESTLE PAK LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ICI).*", "ICI PAK LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(PROCTER GAMBLE).*", "PROCTER GAMBLE PAK PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(FAROOQ STEEL).*", "FAROOQ STEEL INDUSTRY", MyData$Consignee)
MyData$Consignee <- gsub("^(M S SERVICE INDUSTRIES LTD).*", "SERVICE INDUSTRIES LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(NESTLE).*", "NESTLE PAK LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(A B STEEL).*", "A B STEEL", MyData$Consignee)
MyData$Consignee <- gsub("^(3SPARE).*", "3SPARE DEPOT", MyData$Consignee)
MyData$Consignee= gsub("^(A SONS).*", "A SONS CONSULTANT", MyData$Consignee)
MyData$Consignee= gsub("^(A STEEL).*", "A STEEL CASTING", MyData$Consignee)
MyData$Consignee= gsub("^(ABDULLAH IMPEX).*", "ABDULLAH IMPEX", MyData$Consignee)
MyData$Consignee= gsub("^(ABDULLAH INTER).*", "ABDULLAH INTERNATIONAL", MyData$Consignee)
MyData$Consignee= gsub("^(AMEEN TRADING).*", "AMEEN TRADING", MyData$Consignee)
MyData$Consignee= gsub("^(AMEER PHAR).*", "AMEER PHAR PVT LTD", MyData$Consignee)
MyData$Consignee= gsub("^(AMERICAN AMBASSADOR).*", "AMERICAN AMBASSADOR AMERICAN EMBASSY", MyData$Consignee)
MyData$Consignee= gsub("^(AMERICAN CONSULATE).*", "AMERICAN CONSULATE GENERAL", MyData$Consignee)
MyData$Consignee= gsub("^(AMERICAN ELECTRONIC).*", "AMERICAN ELECTRONICS SMC PVT LTD", MyData$Consignee)
MyData$Consignee= gsub("^(AMERICAN EMBASSY).*", "AMERICAN EMBASSY", MyData$Consignee)
MyData$Consignee= gsub("^(AMEER PHAR).*", "AMEER PHAR PVT LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(AMERICAN SAFETY POWER).*", "AMERICAN SAFETY POWER TOOL", MyData$Consignee)
MyData$Consignee <- gsub("^(AMIN IMPEX).*", "AMIN IMPEX", MyData$Consignee)
MyData$Consignee=gsub("^(AMINA CORPORATION).*", "AMINA CORPORATION", MyData$Consignee)
MyData$Consignee=gsub("^(AMMAZ STEEL INDUSTRY).*", "AMMAZ STEEL INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("^(AMNA ENTERPRISE).*", "AMNA ENTERPRISE", MyData$Consignee)
MyData$Consignee=gsub("^(AMSON VACCINES).*", "AMSON VACCINES", MyData$Consignee)
MyData$Consignee=gsub("^(ANEEL BROTHERS).*", "ANEEL BROTHERS", MyData$Consignee)
MyData$Consignee=gsub("^(AQTRA).*", "AQTRA", MyData$Consignee)
MyData$Consignee=gsub("^(ANEEL AND BROTHERS).*", "ANEEL BROTHERS", MyData$Consignee)
MyData$Consignee <- gsub("^(ABOOTT LABORAORIES PAK LTD).*", "ABBOTT LABORATORIES LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(ABBOTT LAB).*", "ABBOTT LABORATORIES LTD", MyData$Consignee)
MyData$Consignee <- gsub("^(THE SHOE HOME).*", "THE SHOE", MyData$Consignee)
MyData$Consignee <- gsub("^(THE SHOE).*", "THE SHOE SHOP", MyData$Consignee)
MyData$Consignee=gsub("^(ANEEL AND BROTHERS).*", "ANEEL BROTHERS", MyData$Consignee)
MyData$Consignee=gsub("^(A INTERNATIONAL).*", "A INTERNATIONAL PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("^(A AND A PIPE INDUST).*", "A AND A PIPE INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("^(A INTERNATIONAL).*", "A INTERNATIONAL PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("^(33 SPARE DEPOT).*", "33 SPARE DEPOT", MyData$Consignee)
MyData$Consignee=gsub("^(3M PAK).*", "3M PAK LTD", MyData$Consignee)
MyData$Consignee=gsub("^(A AND A PIPE INDUST).*", "A AND A PIPE INDUSTRY", MyData$Consignee)
MyData$Consignee=gsub("A A FABRIC", "A A FABRICS PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(A A M INTERNATIONAL IMPORTER).*", "A A M INTERNATIONAL IMPORTER", MyData$Consignee)
MyData$Consignee=gsub("(A A TRADER).*", "A A TRADERS", MyData$Consignee)
MyData$Consignee=gsub("A A ASSAC", "A A ASSAC COMPANY PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("A A FABRIC", "A A FABRICS PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(A A TRADER).*", "A A TRADERS", MyData$Consignee)
MyData$Consignee=gsub("(3 ALC).*", "3 ALC", MyData$Consignee)
MyData$Consignee=gsub("(3 SPARE).*", "3 SPARE DEPOT", MyData$Consignee)
MyData$Consignee=gsub("CHEMICAL", "CHEMICALS", MyData$Consignee)
MyData$Consignee=gsub("ENTERPRISE", "ENTERPRISES", MyData$Consignee)
MyData$Consignee=gsub("CHEMICALSS", "CHEMICALS", MyData$Consignee)
MyData$Consignee=gsub("PAKPVT", "PAK PVT", MyData$Consignee)
MyData$Consignee=gsub("3 4 TELENOR PAK PVT LTD", "TELENOR PAK PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(3 M PAK).*", "3 M PAK PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("(COPR).*", "CORPORATION", MyData$Consignee)
MyData$Consignee=gsub("(COPR).*", "CORPORATION", MyData$Consignee)
MyData$Consignee=gsub("(A B STEEL).*", "A B STEEL", MyData$Consignee)
MyData$Consignee=gsub("COMMISION", "COMMISSION", MyData$Consignee)
MyData$Consignee=gsub("(A F STEEL).*", "A F STEEL REROLLING MILLS", MyData$Consignee)

MyData$Consignee=gsub("(A G DA).*", "A G DAAL MILLS", MyData$Consignee)
MyData$Consignee=gsub("(A FEROZ).*", "A FEROZ AND CO", MyData$Consignee)
MyData$Consignee=gsub("(A F STEEL).*", "A F STEEL REROLLING MILLS", MyData$Consignee)
MyData$Consignee=gsub("PALSTIC", "PLASTIC", MyData$Consignee)
MyData$Consignee=gsub("SON", "SONS", MyData$Consignee)
MyData$Consignee=gsub("SONSS", "SONS", MyData$Consignee)

MyData$Consignee=gsub(" CO", "COMPANY", MyData$Consignee)
MyData$Consignee=gsub("ENTERPRISESS", "ENTERPRISE", MyData$Consignee)
MyData$Consignee=gsub("ENTERPRISES", "ENTERPRISE", MyData$Consignee)

MyData$Consignee=gsub("COMPANY", " COMPANY ", MyData$Consignee)
MyData$Consignee=gsub("COMPANY MPUTERS", "COMPUTERS", MyData$Consignee)

MyData$Consignee=gsub("COMPANY RPORATION", "CORPORATION", MyData$Consignee)
MyData$Consignee=gsub("COMPANY MPANY", "COMPANY", MyData$Consignee)
MyData$Consignee=gsub("A SENTERPRISE", "A S ENTERPRISE", MyData$Consignee)
MyData$Consignee=gsub("S/OIL", "S OIL", MyData$Consignee)
MyData$Consignee=gsub("LLOIDS", "COLLOIDS", MyData$Consignee)
MyData$Consignee=gsub("COMPANY TTON", "COTTON", MyData$Consignee)
MyData$Consignee=gsub("COMPANY NCEPTS", "CONCEPTS", MyData$Consignee)
MyData$Consignee=gsub("COMPANY PORATION", "CORPORATION", MyData$Consignee)
MyData$Consignee=gsub("COMPANY NTAINERS", "CONTAINERS", MyData$Consignee)
MyData$Consignee=gsub("(7 KM).*", "", MyData$Consignee)
MyData$Consignee=gsub("(ALAMEERA APPAREL).*", "ALAMEERA APPAREL PVT LTD", MyData$Consignee)
MyData$Consignee=gsub("MILLSPVT", "MILLS PVT", MyData$Consignee)
MyData$Consignee=gsub("(AB PAK INTE).*", "AB PAK INTERNATIONAL", MyData$Consignee)
MyData$Consignee=gsub("INDUSRTY", "INDUSTRY", MyData$Consignee)



newtab=as.data.frame(table(MyData$Consignee))
View(newtab)


x=gsub("[^0-9A-Za-z///' ]", " ", x)
newa=as.data.frame(table(a))
View(newa)


x=grep("U 613C", MyData$Consignee, value = TRUE)
x=grep("U 3E30", MyData$Consignee, value = TRUE)
x=grep("INDUSRTY", MyData$Consignee, value = TRUE)




View(as.data.frame(x))


MyData$Consignee=gsub("U 613C", "", MyData$Consignee)
MyData$Consignee=gsub("U 3E30", "", MyData$Consignee)
MyData$Consignee=gsub("U 633C", "", MyData$Consignee)
MyData$Consignee=gsub("U 00A0", "", MyData$Consignee)
MyData$Consignee=gsub("U 6", "", MyData$Consignee)
MyData$Consignee=gsub("U 613", "", MyData$Consignee)
MyData$Consignee=gsub("U 61", "", MyData$Consignee)

MyData$Consignee=gsub("13", "", MyData$Consignee)
MyData$Consignee=gsub("  ", " ", MyData$Consignee)
MyData$Consignee=gsub("U 383C", "", MyData$Consignee)
MyData$Consignee=gsub("U 3E31", "", MyData$Consignee)
MyData$Consignee=gsub("1", "", MyData$Consignee)
MyData$Consignee=gsub(" U ", "", MyData$Consignee)




#remove punctuation
x=gsub(' ','',x)

x=gsub("([a-z])([A-Z])", "\\1 \\2", x)

x=grep("AND", MyData$Consignee, value = TRUE)


q=MyData$Consignee
q <-"<U+613C><U+3E30>WAHEED<U+613C><U+3E30>GUL"
q=sub("<U\\+\\w+>\\s*<U\\+\\w+>\\s*", "", q)
q=sub("(<U\\+\\w+>\\s*<U\\+\\w+>\\s*).*", "", q)
q=gsub("<U\\+\\w+>$", "", q)

View(as.data.frame(q))

newq=as.data.frame(table(q))
View(newq)

trimws(gsub("^\\s*<U\\+\\w+>|-", " ", q))



x=grep("^\\s*<U\\+", q, value = TRUE)
head(x)


#check Occurrence
x=grep("MILLS LTD", MyData$Consignee, value = TRUE)


#trim to 30 characters
MyData$Consignee <- strtrim(MyData$Consignee, 30)

f<- strtrim(MyData$Consignee, 35)
freqfunc <- function(x, n){
  tail(sort(table(unlist(strsplit(as.character(x), ", ")))), n)
}

freqfunc(f, 20)

names = colnames(MyData)
names <- MyData$colnames
a=row.names(c)
MyData

# frequency of each company
newtab=as.data.frame(table(MyData$Consignee))
View(newtab)

# write Company frequency
write.csv(newtab,"C:/Users/MICTDATASCIE01/Desktop/comp_v2.csv", row.names = FALSE)

# write whole data
write.csv(MyData,"C:/Users/MICTDATASCIE01/Desktop/WEBOC_V3.csv", row.names = FALSE)
